### ISSUE TITLE
Images turn out half white or pure black

### ISSUE THREAD

**Issue by SunDwarf** [naelstrof/maim#102]
Maim ver: 4.4.62
Desktop: Budgie WM 10.2

Sometimes when taking screenshots, part of the image is white, or completely black. This happens seemingly randomly (I can't repro it consistently, but often randomly).

Examples:
![1493275631](https://cloud.githubusercontent.com/assets/8783751/25471298/58f4d816-2b1e-11e7-8c07-3d8ca20b1d84.png)
![1493275624](https://cloud.githubusercontent.com/assets/8783751/25471299/59055cea-2b1e-11e7-88c3-4f874a21f496.png)
![1493275616](https://cloud.githubusercontent.com/assets/8783751/25471300/590e3f7c-2b1e-11e7-8253-e61a8c05e681.png)

**Comment by naelstrof** [comment]
Oh boy this doesn't look fun to fix. Just wondering though, do you get similar artifacts when recording videos with ffmpeg? (Try running something like `ffmpeg -video_size 1024x768 -framerate 25 -f x11grab -i :0.0+100,200 output.mp4` in a terminal)

Are you running a compositor? Do you have OpenGL support?

I have an idea that it may have something to do with maim not grabbing the entire Xserver, and the image is being changed as it tries to copy it over. I'll let you know when I have something for you to test.

**Comment by SunDwarf** [comment]
>Are you running a compositor?
I believe so (budgie-wm via mutter compositor).

>Do you have OpenGL support?
I assume so, since I'm running on Linux.

>ffmpeg command
No artifacts on all three tries I ran this.

**Comment by naelstrof** [comment]
Could you try the new tag? https://github.com/naelstrof/maim/releases/tag/v5.4.62

I've actually replicated your issue, though it only happens once out of a thousand captures or so. Ffmpeg has the same issues for me but more severely so I'm not even sure if it's related.

This commit is what might fix your issue: https://github.com/naelstrof/maim/commit/e6abb9306bd1a1669b4ded03e0399583a3b20e17

**Comment by naelstrof** [comment]
This is definitely not fixed, despite grabbing the X server, slop had a malformed picture as well. Wish there was an easier way to replicate this..

**Comment by simoniz0r** [comment]
I am having the same issue with maim v3.4.47 and slop slop v4.2.20 using KDE neon User Edition (based on Ubuntu 16.04).  I have the version of maim and slop that is provided from Ubuntu's repos.  The only window that I seem to be able to capture so far without the image being entirely black is the terminal I'm using, Tilix.  Everything else is a completely black image as shown in the OP's first example.

Discord:
![test](https://user-images.githubusercontent.com/16279904/29647973-9ca2d870-8851-11e7-99eb-22f5d6db0d33.png)

Firefox:
![test](https://user-images.githubusercontent.com/16279904/29648018-cafcfc64-8851-11e7-95ca-8736b3770bca.png)

Dolphin:
![test](https://user-images.githubusercontent.com/16279904/29648024-d9e0b3ba-8851-11e7-96b0-be08ac18ad46.png)

Tilix:
![test](https://user-images.githubusercontent.com/16279904/29647990-ad669804-8851-11e7-9f94-ddcfc9189142.png)

**Comment by naelstrof** [comment]
Try updating maim. As of v5.4.65 I use XRender to grab window contents, as well as ask the window manager to redirect window framebuffers (preventing them from being occluded/corrupted) which may be happening here.

You should use the newest maim where possible (which is https://github.com/naelstrof/maim/releases/tag/v5.4.68 as of 8/23/2017)

**Comment by sebastianrakel** [comment]
I had the same problem, installed the new version and the problem is gone.

Running on Archlinux 4.12.8-2-ARCH with intel driver

Intel Corporation HD Graphics 5500

Thank you

**Comment by naelstrof** [comment]
That's great! Yeah redirection should solve the problem, and maim redirects as of v5.4.65.
I'm going to close this now.

**Comment by SunDwarf** [comment]
Hi, I completely forgot I opened this, since you fixed it a while ago. Sorry for not confirming the fix! However, the issue is back, seemingly out of nowhere.

```
$ maim --version
v5.4.68
```

Like before, I can't find a consistent repro.
